LinhNhiShop/LinhNhiShop.Web/Models/ContactDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LinhNhiShop.Web.Models
{
    public class ContactDetailViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Tên không được để trống")]
        public string Name { get; set; }

        [MaxLength(50, ErrorMessage = "Số điện thoại không vượt quá 50 kí tự")]
        public string Phone { get; set; }

        [MaxLength(250, ErrorMessage = "Email không vượt quá 250 kí tự")]
        public string Email { get; set; }

        [MaxLength(250, ErrorMessage = "Website không vượt quá 250 kí tự")]
        public string Website { get; set; }

        [MaxLength(250, ErrorMessage = "Địa chỉ không vượt quá 250 kí tự")]
        public string Adress { get; set; }

        public string Other { get; set; }

        public double? Lat { get; set; }

        public double? Lng { get; set; }

        public bool Status { get; set; }
    }
}

LinhNhiShop/LinhNhiShop.Web/Controllers/ContactDetailController.cs
using AutoMapper;
using BotDetect.Web.Mvc;
using LinhNhiShop.Common;
using LinhNhiShop.Model.Models;
using LinhNhiShop.Service;
using LinhNhiShop.Web.Infrastructue.Extentions;
using LinhNhiShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinhNhiShop.Web.Controllers
{
    public class ContactDetailController : Controller
    {
        IContactDetailService _contactDetailService;
        IFeedbackService _feedbackService;

        public ContactDetailController(IContactDetailService contactDetailService, IFeedbackService feedbackService)
        {
            this._contactDetailService = contactDetailService;
            this._feedbackService = feedbackService;
        }
        // GET: ContactDetail
        public ActionResult Index()
        {
            var feedbackViewModel = new FeedbackViewModel();
            feedbackViewModel.ContactDetailViewModel = GetContactDetailViewModel();

            return View(feedbackViewModel);
        }

        [HttpPost]
        [CaptchaValidation("CaptchaCode", "ContactDetailCaptcha", "Mã xác nhận không đúng!")]
        public ActionResult SendFeedback(FeedbackViewModel feedbackViewModel)
        {
            if (ModelState.IsValid)
            {
                Feedback feedback = new Feedback();
                feedback.UpdateFeedback(feedbackViewModel);
                _feedbackService.Create(feedback);
                _feedbackService.Save();

                ViewData["SuccessMsg"] = "Gửi phản hồi thành công";

                string content = System.IO.File.ReadAllText(Server.MapPath("~/Assets/client/template/contact_template.html"));
                content = content.Replace("{{Name}}", feedbackViewModel.Name);
                content = content.Replace("{{Email}}", feedbackViewModel.Email);
                content = content.Replace("{{Message}}", feedbackViewModel.Message);

                var adminEmail = ConfigHelper.GetByKey("AdminEmail");
                MailHelper.SendMail(adminEmail, "Thông tin liên hệ từ Website", content);

                feedbackViewModel.Name = string.Empty;
                feedbackViewModel.Email = string.Empty;
                feedbackViewModel.Message = string.Empty;
            }
            feedbackViewModel.ContactDetailViewModel = GetContactDetailViewModel();

            return View("Index", feedbackViewModel);
        }

        private ContactDetailViewModel GetContactDetailViewModel()
        {
            var contectDetailModel = _contactDetailService.GetDefaultContact();
            return Mapper.Map<ContactDetail, ContactDetailViewModel>(contectDetailModel);
        }
    }
}

LinhNhiShop/LinhNhiShop.Web/Views/ContactDetail/Index.cshtml
@model LinhNhiShop.Web.Models.FeedbackViewModel
@using BotDetect.Web.Mvc;

@{
    ViewBag.Title = "Liên hệ";
    Layout = "~/Views/Shared/Layouts.cshtml";
}


<input type="hidden" id="hidContactDetail" value="@Model.ContactDetailViewModel.Adress" />
@section footerJS{
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZWH3sqMrPM-2QlGIKV5AM4YrCSoGG9Jg"></script>
    <script src="~/Assets/client/js/controllers/contactDetail.js"></script>
}
<style>
    #map {
        height: 400px;
    }
</style>

<link href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl" rel="stylesheet" type="text/css" />

<input type="hidden" id="hidAddress" value="@Model.ContactDetailViewModel.Name<br />Điện thoại: @Model.ContactDetailViewModel.Phone <br />Địa chỉ: @Model.ContactDetailViewModel.Adress" />
<input type="hidden" id="hidName" value="@Model.ContactDetailViewModel.Name" />
<input type="hidden" id="hidLat" value="@Model.ContactDetailViewModel.Lat" />
<input type="hidden" id="hidLng" value="@Model.ContactDetailViewModel.Lng" />

<div class="main">
    <div class="reservation_top">
        <div class="contact_right">
            <h3>Thông tin liên hệ</h3>
            <div class="contact-form">
                <address class="address">
                    <p>@Model.ContactDetailViewModel.Adress</p>
                    <dl>
                        <dt> </dt>
                        <dd>Điện thoại:<span> @Model.ContactDetailViewModel.Phone</span></dd>
                        <dd>E-mail:&nbsp; <a href="mailto:@(Model.ContactDetailViewModel.Email)">@Model.ContactDetailViewModel.Email</a></dd>
                    </dl>
                </address>
                <div class="clearfix"></div>
                <div id="map"></div>
            </div>
        </div>
    </div>
    <div class="reservation_top">
        <div class="contact_right">
            <h3>Gửi thông tin liên hệ</h3>
            <div class="contact-form">
                @using (Html.BeginForm("SendFeedback", "ContactDetail", FormMethod.Post))
                {
                    if (ViewData["SuccessMsg"] != null)
                    {
                        <div class="alert alert-success" role="alert">
                            <strong>Bạn đã gửi phản hồi thành công.</strong>
                            <br />Chúng tôi sẽ liên hệ lại sớm nhất có thể.
                            <br />Xin cảm ơn!
                        </div>
                    }

                    @Html.ValidationSummary(false, "", new { @class = "error" });

                    @Html.TextBoxFor(model => model.Name, new { @class = "textbox", @placeholder = "Tên" });
                    @Html.TextBoxFor(model => model.Email, new { @class = "textbox", @placeholder = "Email" });
                    @Html.TextAreaFor(model => model.Message, new { @placeholder = "Để lại lời nhắn..." });

                    MvcCaptcha contactDetailCaptcha = new MvcCaptcha("ContactDetailCaptcha");
                    @Html.Captcha(contactDetailCaptcha);
                    @Html.TextBox("CaptchaCode");
                    <input type="submit" value="Gửi">
                    <div class="clearfix"> </div>
                }
            </div>
        </div>
    </div>
</div>